language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/1150/GJBL60vlZTUiHJOZjosvqCdh

env:
  global:
    - secure: "Szy30QpDk0TKn80liCnSjeaLJb0Tz09hEQoX+jgp2jnOOpgW422ZgRsDf7rEXU2pbqE3s+kue9+MLhic2Ar8XmBcPrKVKP2tFnqxMjLgNSDQpafCEWyypdjQHI2wsqYbF5ZV8ln7ymmI8Aw05ZpnObCzLc+x0PbSDAbL6zNaWDQ="
    - secure: "SXa8epdU4wsmldyVO4BP2U32cM8IzrGt1Fyk6KzsXJ8ewKy3wkA1bgKmhgbPpDX7q8zQXMxWdvpxEgU4gn+bASChLayVgOxFLjGoqcyGjbta8RswZW/BnJ/GYswiE8vl03YDPeFVBdmW9R6u7fLPYtgyUV71OjBMGgDjG0LLdtQ="